version: '3.8'

services:
  app:
    build: .
    expose:
      - "5432"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/check_device

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=check_device
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: